import { Club } from './types';

export const mockClubs: Club[] = [
  {
    id: '1',
    name: '戏剧社',
    nameEn: 'Drama Club',
    category: '文艺',
    president: '林思妤',
    presidentEn: 'Lin Siyu',
    presidentContact: 'linsiyu@drama.edu.cn',
    description: '我们是一个充满激情的戏剧表演团体，致力于舞台艺术的探索与创新。成员来自各专业，共同排练并呈现原创或改编剧目。',
    descriptionEn: 'A passionate drama performance group dedicated to exploring and innovating stage arts. Members from all majors come together to rehearse and perform original or adapted plays.',
    tags: ['表演', '创作', '舞台', '剧本', '团队合作'],
    tagsEn: ['Performance', 'Creation', 'Stage', 'Playwriting', 'Teamwork'],
    memberCount: 45,
    weeklyHours: 6,
    rating: 4.7,
    profile: {
      perform: 5,
      creative: 4,
      sport: 1,
      academic: 2,
      social: 3,
      hours: 5,
      role: ['leader', 'executor'],
      vibe: 'energetic',
      schedule: 'regular',
    },
    socialMedia: {
      wechat: '戏剧社官方公众号',
      xiaohongshu: 'https://xiaohongshu.com/drama-club',
      douyin: 'https://douyin.com/drama-club',
    },
    activities: [
      { id: 'a1', title: '年度大戏《等待戈多》', titleEn: 'Annual Production: Waiting for Godot', date: '2024-05-15', description: '改编自贝克特经典荒诞剧，演出历时3天，观众超500人', descriptionEn: "An adaptation of Beckett's classic absurdist play, running 3 days with over 500 audience members.", participants: 20 },
      { id: 'a2', title: '即兴戏剧工作坊', titleEn: 'Improv Theater Workshop', date: '2023-11-20', description: '邀请专业导演带领成员进行即兴表演训练', descriptionEn: 'A professional director led members through intensive improvisation training.', participants: 30 },
      { id: 'a3', title: '校际戏剧节金奖', titleEn: 'Inter-College Drama Festival — Gold Award', date: '2022-12-10', description: '参加省级校际戏剧节并荣获最佳剧目金奖', descriptionEn: 'Won Best Production at the provincial inter-college drama festival.', participants: 15 },
    ],
    reviews: [
      {
        id: 'r1', anonymous: true, verified: true, enrollYear: 2023,
        content: '社团氛围超级好，导演很专业，每次排练都能学到新东西。强烈推荐喜欢表演的同学加入！',
        contentEn: 'Amazing vibe — the director is super professional and I learn something new every rehearsal. Highly recommend for anyone who loves performing!',
        ratings: { atmosphere: 5, timeValue: 4, activity: 5, management: 4, newbieFriendly: 5 },
        createdAt: '2024-09-01', likes: 24,
      },
      {
        id: 'r2', anonymous: true, verified: true, enrollYear: 2022,
        content: '时间投入比较多，但收获也很大。演出那天站在舞台上的感觉无与伦比。',
        contentEn: "It's a big time commitment, but the payoff is real. Standing on that stage on performance night is an indescribable feeling.",
        ratings: { atmosphere: 4, timeValue: 3, activity: 5, management: 4, newbieFriendly: 4 },
        createdAt: '2024-08-15', likes: 18,
      },
      {
        id: 'r3', anonymous: true, verified: true, enrollYear: 2023,
        content: '对零基础也很友好，有专门的新人培训。就是排练时间有时候会临时变动。',
        contentEn: 'Very beginner-friendly with dedicated newcomer training. The only downside is rehearsal schedules can change last minute.',
        ratings: { atmosphere: 5, timeValue: 4, activity: 4, management: 3, newbieFriendly: 5 },
        createdAt: '2024-07-20', likes: 12,
      },
    ],
  },
  {
    id: '2',
    name: '摄影协会',
    nameEn: 'Photography Society',
    category: '文艺',
    president: '陈宇航',
    presidentEn: 'Chen Yuhang',
    presidentContact: 'chenyuhang_photo',
    description: '用镜头记录生活，探索光影之美。我们定期举办摄影课程、外拍活动和展览，欢迎所有热爱摄影的同学。',
    descriptionEn: 'We use our lenses to capture life and explore the beauty of light. Regular photography courses, outdoor shoots, and exhibitions. All shutterbugs welcome.',
    tags: ['摄影', '后期', '展览', '创作', '风景'],
    tagsEn: ['Photography', 'Post-processing', 'Exhibition', 'Creation', 'Landscape'],
    memberCount: 62,
    weeklyHours: 3,
    rating: 4.5,
    profile: {
      perform: 2,
      creative: 5,
      sport: 2,
      academic: 3,
      social: 2,
      hours: 3,
      role: ['executor', 'member'],
      vibe: 'professional',
      schedule: 'flexible',
    },
    socialMedia: {
      wechat: '摄影协会',
      xiaohongshu: 'https://xiaohongshu.com/photo-club',
      weibo: 'https://weibo.com/photo-club',
    },
    activities: [
      { id: 'a4', title: '年度摄影展「城市脉搏」', titleEn: 'Annual Exhibition: City Pulse', date: '2024-04-20', description: '展出会员优秀作品120余幅，吸引观展人数800+', descriptionEn: 'Featured 120+ member works, attracting over 800 visitors.', participants: 50 },
      { id: 'a5', title: '夜景摄影外拍活动', titleEn: 'Night Photography Shoot', date: '2023-10-05', description: '前往城市地标进行集体夜景拍摄，并现场教学长曝光技巧', descriptionEn: 'Group shoot at city landmarks with on-site long-exposure technique teaching.', participants: 25 },
      { id: 'a6', title: 'Lightroom后期修图工作坊', titleEn: 'Lightroom Editing Workshop', date: '2022-09-18', description: '邀请摄影师讲解专业后期处理技术', descriptionEn: 'A professional photographer shared advanced post-processing techniques.', participants: 40 },
    ],
    reviews: [
      {
        id: 'r4', anonymous: true, verified: true, enrollYear: 2023,
        content: '老手带新手的模式很好，学到了很多构图和用光技巧。外拍活动特别有意思！',
        contentEn: 'The mentor system is great — I learned so much about composition and lighting. The outdoor shoots are especially fun!',
        ratings: { atmosphere: 4, timeValue: 5, activity: 5, management: 4, newbieFriendly: 5 },
        createdAt: '2024-09-10', likes: 31,
      },
      {
        id: 'r5', anonymous: true, verified: true, enrollYear: 2022,
        content: '时间比较灵活，不需要强制参加所有活动。对于想利用课余时间学摄影的同学很合适。',
        contentEn: 'Very flexible — no pressure to attend every event. Perfect if you want to learn photography in your spare time.',
        ratings: { atmosphere: 4, timeValue: 5, activity: 4, management: 5, newbieFriendly: 4 },
        createdAt: '2024-08-01', likes: 19,
      },
      {
        id: 'r6', anonymous: true, verified: true, enrollYear: 2023,
        content: '社团活动质量很高，展览布置也很专业。希望能多一些人像摄影的教学内容。',
        contentEn: 'Great event quality and very professional exhibition setups. Would love more portrait photography workshops.',
        ratings: { atmosphere: 3, timeValue: 4, activity: 5, management: 4, newbieFriendly: 4 },
        createdAt: '2024-06-30', likes: 8,
      },
    ],
  },
  {
    id: '3',
    name: '编程俱乐部',
    nameEn: 'Coding Club',
    category: '科技',
    president: '张明轩',
    presidentEn: 'Zhang Mingxuan',
    presidentContact: 'zhangmx@cs.edu.cn',
    description: '我们热爱代码，热爱创造。从算法竞赛到项目开发，从Web到AI，这里有最前沿的技术探讨和最友好的学习社区。',
    descriptionEn: 'We build things with code. From algorithms to apps, we learn by doing. Weekly hackathons, project showcases, and tech talks.',
    tags: ['编程', '算法', 'AI', '项目开发', '竞赛', '开源'],
    tagsEn: ['Coding', 'Algorithms', 'AI', 'Project Dev', 'Competitions', 'Open Source'],
    memberCount: 80,
    weeklyHours: 5,
    rating: 4.8,
    profile: {
      perform: 1,
      creative: 4,
      sport: 1,
      academic: 5,
      social: 2,
      hours: 4,
      role: ['executor', 'leader'],
      vibe: 'professional',
      schedule: 'regular',
    },
    socialMedia: {
      wechat: 'CodeClub编程社',
      douyin: 'https://douyin.com/code-club',
      weibo: 'https://weibo.com/code-club',
    },
    activities: [
      { id: 'a7', title: '24小时黑客马拉松', titleEn: '24-Hour Hackathon', date: '2024-03-22', description: '120名参赛者组队开发创新项目，主题为「AI+校园生活」', descriptionEn: '120 participants formed teams to build innovative projects on the theme "AI + Campus Life".', participants: 120 },
      { id: 'a8', title: 'ACM校内选拔赛', titleEn: 'ACM Campus Qualifier', date: '2023-11-11', description: '算法竞赛校内选拔，前三名代表学校参加省级比赛', descriptionEn: 'Internal algorithm competition; top 3 represented the school at the provincial contest.', participants: 60 },
      { id: 'a9', title: 'LLM应用开发研讨会', titleEn: 'LLM Application Dev Summit', date: '2022-12-03', description: '探讨大语言模型在实际项目中的应用，分享开发经验', descriptionEn: 'Explored large language model applications in real projects and shared development experience.', participants: 45 },
    ],
    reviews: [
      {
        id: 'r7', anonymous: true, verified: true, enrollYear: 2022,
        content: '技术氛围浓厚，大佬很多但也很愿意分享。黑客马拉松是我大学最难忘的经历之一。',
        contentEn: 'Super strong tech culture — the seniors know a lot and are always happy to share. The hackathon is one of my best college memories.',
        ratings: { atmosphere: 5, timeValue: 4, activity: 5, management: 5, newbieFriendly: 4 },
        createdAt: '2024-09-05', likes: 42,
      },
      {
        id: 'r8', anonymous: true, verified: true, enrollYear: 2023,
        content: '项目实战机会多，对找工作很有帮助。管理很规范，每次活动都组织得井井有条。',
        contentEn: 'Tons of hands-on project experience — really helpful for job hunting. Events are well-organized and management is professional.',
        ratings: { atmosphere: 4, timeValue: 4, activity: 5, management: 5, newbieFriendly: 3 },
        createdAt: '2024-07-12', likes: 35,
      },
      {
        id: 'r9', anonymous: true, verified: true, enrollYear: 2024,
        content: '零基础可以加入，有专门的新手学习路线。但进阶活动对基础要求比较高。',
        contentEn: 'Beginners are welcome and there is a dedicated learning path. Just note that advanced activities have a higher skill bar.',
        ratings: { atmosphere: 5, timeValue: 4, activity: 4, management: 4, newbieFriendly: 4 },
        createdAt: '2024-05-18', likes: 27,
      },
    ],
  },
  {
    id: '4',
    name: '篮球队',
    nameEn: 'Basketball Team',
    category: '体育',
    president: '王俊博',
    presidentEn: 'Wang Junbo',
    presidentContact: 'wangjunbo_bb',
    description: '我们不只是打篮球，更是在培养团队精神和拼搏意志。队内训练科学系统，每年参加多项校际联赛，欢迎有激情的球员加入。',
    descriptionEn: 'More than just basketball — we build teamwork and resilience. Scientific training system, competing in inter-college leagues every year.',
    tags: ['篮球', '团队', '竞技', '训练', '联赛'],
    tagsEn: ['Basketball', 'Teamwork', 'Competition', 'Training', 'Leagues'],
    memberCount: 30,
    weeklyHours: 8,
    rating: 4.6,
    profile: {
      perform: 3,
      creative: 1,
      sport: 5,
      academic: 1,
      social: 5,
      hours: 5,
      role: ['executor', 'member'],
      vibe: 'energetic',
      schedule: 'regular',
    },
    socialMedia: {
      wechat: '篮球队',
      douyin: 'https://douyin.com/basketball-team',
      weibo: 'https://weibo.com/basketball-team',
    },
    activities: [
      { id: 'a10', title: '校际篮球联赛季军', titleEn: 'Inter-College Basketball League — 3rd Place', date: '2024-05-30', description: '代表学院参加全校联赛，历经12场激烈角逐获得季军', descriptionEn: 'Competed in 12 intense games across the school-wide league, finishing third.', participants: 15 },
      { id: 'a11', title: '三人篮球街头赛', titleEn: '3-on-3 Street Basketball Tournament', date: '2023-09-24', description: '组织校内3v3街球大赛，16支队伍参与，现场氛围热烈', descriptionEn: 'Organized a 3v3 campus tournament with 16 teams in an electric atmosphere.', participants: 64 },
      { id: 'a12', title: '篮球夏令营', titleEn: 'Basketball Summer Camp', date: '2022-07-15', description: '邀请专业教练为成员进行为期一周的集训', descriptionEn: 'Professional coaches ran an intensive week-long training camp for members.', participants: 25 },
    ],
    reviews: [
      {
        id: 'r10', anonymous: true, verified: true, enrollYear: 2022,
        content: '训练强度大但效果明显，技术提升很快。队友之间感情很好，赢球的时候特别爽！',
        contentEn: 'Training is intense but the improvement is real and fast. Great team chemistry — nothing beats winning together!',
        ratings: { atmosphere: 5, timeValue: 3, activity: 5, management: 4, newbieFriendly: 3 },
        createdAt: '2024-08-20', likes: 29,
      },
      {
        id: 'r11', anonymous: true, verified: true, enrollYear: 2023,
        content: '时间投入比较多，每周训练加比赛要8小时以上。但对于真正热爱篮球的人来说完全值得。',
        contentEn: 'Big time commitment — 8+ hours a week between training and games. But if you truly love basketball, it is absolutely worth it.',
        ratings: { atmosphere: 5, timeValue: 3, activity: 5, management: 4, newbieFriendly: 3 },
        createdAt: '2024-06-10', likes: 21,
      },
      {
        id: 'r12', anonymous: true, verified: true, enrollYear: 2023,
        content: '教练很专业，战术体系完整。比较遗憾的是对新人练习机会较少，竞争激烈。',
        contentEn: 'Very professional coaching with a solid tactical system. Downside: fewer practice reps for newcomers — competition for spots is fierce.',
        ratings: { atmosphere: 4, timeValue: 3, activity: 4, management: 5, newbieFriendly: 2 },
        createdAt: '2024-04-05', likes: 14,
      },
    ],
  },
  {
    id: '5',
    name: '辩论社',
    nameEn: 'Debate Society',
    category: '学术',
    president: '刘雅琪',
    presidentEn: 'Liu Yaqi',
    presidentContact: 'liu_yaqi@debate.edu.cn',
    description: '思维碰撞，言辞交锋。我们在辩论中磨砺逻辑，在争论中寻找真理。无论你是辩论新手还是经验丰富的辩手，这里都欢迎你。',
    descriptionEn: 'We argue for fun (and to get better at thinking). Weekly debate rounds, critical thinking workshops, and regional competitions.',
    tags: ['辩论', '逻辑思维', '公共演讲', '批判性思维', '竞赛'],
    tagsEn: ['Debate', 'Logic', 'Public Speaking', 'Critical Thinking', 'Competition'],
    memberCount: 35,
    weeklyHours: 4,
    rating: 4.4,
    profile: {
      perform: 5,
      creative: 3,
      sport: 1,
      academic: 5,
      social: 4,
      hours: 3,
      role: ['leader', 'executor'],
      vibe: 'professional',
      schedule: 'regular',
    },
    socialMedia: {
      wechat: '辩论社官方',
      xiaohongshu: 'https://xiaohongshu.com/debate-club',
    },
    activities: [
      { id: 'a13', title: '省级高校辩论联赛亚军', titleEn: 'Provincial College Debate League — Runner-up', date: '2024-06-08', description: '参加省内高校辩论联赛，经历激烈角逐获得亚军', descriptionEn: 'Competed in the provincial inter-college debate league and finished runner-up.', participants: 8 },
      { id: 'a14', title: '年度校内辩论赛', titleEn: 'Annual Campus Debate Championship', date: '2023-12-01', description: '组织全校20支队伍参与的辩论大赛，主题为科技与人文', descriptionEn: 'Organized a school-wide tournament with 20 teams on the theme of Technology & Humanities.', participants: 80 },
      { id: 'a15', title: 'TED演讲训练营', titleEn: 'TED Talk Training Camp', date: '2022-10-22', description: '邀请演讲教练进行公共演讲技能专项训练', descriptionEn: 'A speech coach delivered a focused workshop on public speaking skills.', participants: 30 },
    ],
    reviews: [
      {
        id: 'r13', anonymous: true, verified: true, enrollYear: 2023,
        content: '逻辑思维和表达能力提升很显著。赛前备战很辛苦，但站上舞台时充满成就感。',
        ratings: { atmosphere: 4, timeValue: 4, activity: 5, management: 4, newbieFriendly: 4 },
        createdAt: '2024-09-15', likes: 33,
      },
      {
        id: 'r14', anonymous: true, verified: true, enrollYear: 2022,
        content: '氛围很好，讨论问题很深入。对提升批判性思维帮助很大，推荐理工科同学来锻炼表达。',
        ratings: { atmosphere: 5, timeValue: 4, activity: 4, management: 4, newbieFriendly: 4 },
        createdAt: '2024-07-28', likes: 28,
      },
      {
        id: 'r15', anonymous: true, verified: true, enrollYear: 2023,
        content: '有完整的培训体系，从立论到驳论都有系统教学。时间安排相对规律，不会太混乱。',
        ratings: { atmosphere: 4, timeValue: 5, activity: 4, management: 5, newbieFriendly: 5 },
        createdAt: '2024-05-30', likes: 17,
      },
    ],
  },
];
